# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2780d3840ce36b2da286f87a478561a5eed74ccdffe7ee993e7dd1121fb2aa9f9569fe59edee6ee8a7801127d72375082657c951e601d6f9d6e141096aa7afaa

test:
  secret_key_base: a8af1c27d7fb654f96052ba44f8ac81b476caecda660da1f12ad417e276c95e849ff864045e060262cc1f36fd0638ecf125cff4f539dd46036648a38cabe67bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
